### ISSUE TITLE
'pwa' is not a registered tag library. Must be one of:

### ISSUE THREAD

**Issue by daaslabs** [shubham1710/Fenice-Network#3]
Hi Team,
When I am trying to set up this project I got an error. I thing pwa app is missing on github please upload it
TemplateSyntaxError at /hiring/
'pwa' is not a registered tag library. Must be one of:

**Comment by shubham1710** [comment]
Don't worry! Just remove pwa and it would work fine. Pwa was actually to make it a progressive web app. Its a python library available to install and use.
Omitting it wont cause any problems.
